version: "3.5"

services:
  mysql:
    image: mysql:8.0
    container_name: mrgen_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${RDS_DB_NAME:-mrgen}
      MYSQL_USER: ${RDS_USERNAME:-mrgen}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}

  backend:
    image: "aswwu/saml:${IMAGE_TAG:-latest}"
    build: .
    container_name: mrgen_server
    restart: always
    expose:
      - 8000
    volumes:
      - webroot:/home/mrgen/webroot
    networks:
      - backend
      - frontend
    depends_on:
      - mysql
    environment:
      DJANGO_ENV: ${DJANGO_ENV:-prod}
      DJANGO_RDS: ${DJANGO_RDS:-prod}
      DJANGO_SECRET_KEY:
      DJANGO_HOST_DOMAIN:
      RDS_HOSTNAME: mysql
      RDS_DB_NAME: ${RDS_DB_NAME:-mrgen}
      RDS_USERNAME: ${RDS_USERNAME:-mrgen}
      RDS_PASSWORD:
      WATCHMAN_API_KEY:
      REPAIRSHOPR_API_KEY:

volumes:
  mysql:
    name: mrgen_mysql
  webroot:
    name: mrgen_webroot

networks:
  frontend:
    name: mrgen_frontend
  backend:
    name: mrgen_backend
