# Generated by Django 2.1.5 on 2019-01-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchman_id', models.TextField()),
                ('repairshopr_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchmanWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.TextField()),
                ('warning_id', models.TextField()),
                ('date_reported', models.DateField()),
                ('date_resolved', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Customer')),
            ],
        ),
    ]
