# Generated by Django 2.2 on 2019-04-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('num_current_warnings', models.IntegerField(default=0)),
                ('num_resolved_warnings', models.IntegerField(default=0)),
                ('num_mac_os', models.IntegerField(default=0)),
                ('num_windows_os', models.IntegerField(default=0)),
                ('num_linux_os', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
